royhills/arp-scan

arp-scan.1, arp-scan.c
the link http://www.nta-monitor.com/tools-resources/security-tools/arp-scan seems to be outdated; it takes you to a listing of their tools rather than the arp-scan tool page itself.
i found all matches and replaced them with what i think the link should be pointing at: http://www.nta-monitor.com/tools-resources/security-tools/arp-scan/
~/Git/arp-scan $ grep -rn http://www.nta-monitor.com/tools/arp-scan/ .
./arp-scan.c:490:      printf("Starting %s with %u hosts (http://www.nta-monitor.com/tools/arp-scan/)\n",
./arp-scan.c:1198:   fprintf(stdout, "See the arp-scan homepage at http://www.nta-monitor.com/tools/arp-scan/\n");
./arp-scan.1:640:Starting arp-scan 1.4 with 256 hosts (http://www.nta-monitor.com/tools/arp-scan/)
./arp-scan.1:677:Starting arp-scan 1.4 with 8 hosts …
=> replace link that should be pointing directly to the project's page

arp-fingerprint
Hi,
I added a new option for the "arp-fingerprint" script - "-l"; AKA "localnet".
The tool should work as it did before, but if the user adds the "-l" flag, the script will use arp-scan to detect all IP addresses in the local network (it will use the "--localnet" flag in arp-scan), and then run the arp-fingerprint procedure for each of those targets.
=> Added "localnet" option

arp-scan.c, arp-scan.h
Hi, 
I think it fulfills this TODO in your wiki:
> Use source_mac rather than interface_mac in the pcap filter, as suggested by Justin Keogh. This will
> allow arp-scan to receive packets with spoofed MAC source addresses. 
arp_sha contains the value if interface_mac if not set, which is what is expected. I do not see any side effect.
Cheers,
Cedric
=> Replaced interface address by ARP source address for pcap filter

link-packet-socket.c
if there's a permission error (or another error), the returned handle
will be null and the subsequent dereference will crash the program.
=> link_open: do not crash when run as non-root

acinclude.m4
exit() is defined in stdlib.h which is not included by default
so this will on namespace-clean system such as musl libc raise
the warning "implicit declaration of function 'exit'", which
will cause bogus configure results when the user has -Werror
or -Werror-implicit-function-declaration (highly recommended)
in his CFLAGS.
closes #17
=> acinclude.m4: use return instead of exit()

link-packet-socket.c
By reordering the memcpy and link_close calls, this file no longer uses memory after free'ing. All tests still work and I don't see anything that could go wrong with this.
=> Fix use after free in link-packet-socket.c

arp-scan.c
As discussed on https://github.com/royhills/arp-scan/issues/25
Example output:
```
192.168.0.108	02:01:9c:45:40:2d	(Unknown: locally administered)
```
=> If it's a 'locally administered' MAC / OUI, say so.

acinclude.m4
Even if gcc accepts the -fstack-protector argument, it is possible that
the libssp support library is missing. Detect this by linking instead
of just compiling.
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[Retrieved from:
https://git.buildroot.net/buildroot/tree/package/arp-scan/0001-configure-try-linking-to-detect-stack-protector-supp.patch]
=> configure: try linking to detect stack-protector support

get-iab
The current URL has an invalid certificate, the simplest is to use the same kind of URL as for the OUI URL.
=> Update IAB URL

ChangeLog, Makefile.am, arp-scan.1, arp-scan.c, arp-scan.h, check-decode, format.c, utils.c
Increase the output format flexibility with a *--format* option. This option specifies an output format string consisting of text and fields: text is output verbatim; fields output the appropriate value with an optional width and right or left justification. When *--format* is specified, the details for each responding host are displayed according to the format string.
The concept is based on that used by the Debian *dpkg-query* command for custom output formats with the *--showformat* option.
Resolves #57 
Resolves #71
=> Increased output format flexibility with --format option

ChangeLog, arp-scan.1.dist, arp-scan.c
Change the --format short option character from -k to -F. The -F character became free when the --iabfile option was removed by https://github.com/royhills/arp-scan/pull/79, and is a more logical choice.
=> Change format short option from -k to -F

ChangeLog, Makefile.am, arp-scan.1.dist, arp-scan.c
Install `mac-vendor.txt` to `$(sysconfdir)/$(PACKAGE)` instead of `$(pkgdatadir)`. With a default `./configure` this will be `/usr/local/etc/arp-scan`.  For a binary package it will typically be `/etc/arp-scan`. This change is because users may add local entries to `mac-vendor.txt` that they want to preserve between package upgrades.
=> Install mac-vendor.txt to $(sysconfdir)/$(PACKAGE) instead of $(pkgdatadir)

ChangeLog, arp-scan.c
This breaks some old toolchains e.g. autoconf 2.69/gcc 4.9.2 on Debian Jessie.
=> Remove C99 "for (int i=0..." syntax

ChangeLog, Makefile.am, check-error
Move tests for errors from check-run1 to new check-error script. Add some new tests to increase code coverage.
=> Move error tests to new check-error script

.github/workflows/code-coverage.yml, .github/workflows/codeql.yml
Install libcap-dev for all Linux action runs so arp-scan gets built with POSIX.1e capabilities support.
=> Install libcap-dev for code-coverage and codeql runs

ChangeLog, Makefile.am, NEWS.md
`make install` will install the arp-scan executable with CAP_NET_RAW capability if it can, otherwise (if the `setcap` command doesn't exist or if it fails) then it will fallback to using SUID.
Note that `setcap` can fail if the arp-scan exectable is installed to a filesystem that does not support extended attributes, e.g. NFS.
=> Install executable with CAP_NET_RAW capability or fallback to SUID

ChangeLog, Makefile.am
Modify the `PKGSYSCONFDIR` macro definition in `Makefile.am` so `arp-scan` looks in the correct directory for the `mac-vendor.txt` file.
Fixes https://github.com/royhills/arp-scan/issues/107
=> Correct mac-vendor.txt directory location

ChangeLog, arp-scan.c, error.c, format.c, link-bpf.c, link-dlpi.c, link-packet-socket.c, utils.c, wrappers.c
Standardise code formatting using `clang-format` as a guideline.
Config file:
```
BasedOnStyle: LLVM
IndentWidth: 3
AlwaysBreakAfterDefinitionReturnType: All
IndentCaseLabels: true
```
=> Standardise code formatting

ChangeLog, arp-scan.1.dist, arp-scan.c
When a capabilities aware build of `arp-scan` runs as root, it loses all root's special permissions (apart from briefly possessing the CAP_NET_RAW capability which is irrelevant for this change) and becomes an unprivileged process with UID 0.  This can cause the speculative open of `ieee-oui.txt` and `mac-vendor.txt` in the current directory to fail with `EACCES` if UID 0 lacks execute permission.
This change causes an `EACCES` (Permission Denied) to be treated as if the file were not present, causing arp-scan to load the system file (e.g. `/usr/share/arp-scan/ieee-oui.txt`) instead.
Issue: https://github.com/royhills/arp-scan/issues/119
=> Treat EACCES as ENOENT when opening mapping files in current directory

ChangeLog, NEWS.md, configure.ac
Add "-git" to development versions to indicate that it's not a release version.
From this point, version numbers will change like this:
```
10.0.0     Release version
10.0.1-git Development version
10.0.1     Release version
```
=> Add "-git" to version number to indicate development version

arp-scan.h, utils.c
Use assert statements for things that should never happen.
I think the last "Shouldn't happen" error was closed off about a year ago in https://github.com/royhills/arp-scan/issues/67 (thanks @mrquincle).
So these things and other "this won't ever happen" checks will be replaced by assert() statements with this pull request.  I'm fairly confident that these conditions really won't happen now, and the use of assert() should encourage the submission of bug reports if any of them do actually happen. NDEBUG is left undefined.
=> Use assert statements for things that should never happen

arp-scan.c, utils.c
Remove switch break statements when the previous statement obviously won't return.
The statements removed should be obvious to the compiler. There is one that has been left in which is obvious to me but is not obvious to gcc 12.2 (not sure who's correct tbh!).
=> Remove switch break statements when the previous statement obviously won't return

ChangeLog, mac-vendor.txt
Updated contents of `mac-vendor.txt` from the OpenBSD 1.10.0 ports patch.
=> Updated mac-vendor.txt from OpenBSD 1.10.0 ports patch

.github/workflows/c-cpp.yml, ChangeLog, link-bpf.c
Add the `link-bpf.c` patch from the OpenBSD 1.10.0 port. This should be applicable to all BPF users (OpenBSD, NetBSD, FreeBSD, DragonflyBSD, macOS).
=> Add OpenBSD link-bpf patch

arp-scan.c, configure.ac
This is based on the OpenBSD 1.10.0 ports patch. Modified slightly to check for pledge(2) in `configure.ac` and only include the pledge code if we have it.
=> Check for the OpenBSD pledge(2) function and use if present.

arp-scan.c
Include `Built with OpenBSD pledge(2) support.` in the `arp-scan --version` output if applicable.
=> Display OpenBSD pledge(2) support in version output

ChangeLog, NEWS.md, arp-scan.c
Call `pcap_freecode()` to free the BPF program after calling `pcap_setfilter()`.
=> Call pcap_freecode() to free the BPF program

ChangeLog, NEWS.md, arp-scan.h
Disable promiscuous mode on the network interface. The interface does not need to be put into promiscuous mode to receive ARP responses.
=> Disable promiscuous mode

ChangeLog, NEWS.md, README.md, arp-fingerprint.1, arp-scan.1.dist, mac-vendor.txt
Update the links to the old MediaWiki `http://www.royhills.co.uk/wiki/` or `http://www.nta-monitor.com/wiki/` to the new github wiki pages at `https://github.com/royhills/arp-scan/wiki`.
=> Use github wiki URL in arp-scan documentation

ChangeLog, arp-scan.c
Always warn if remove_host() is called on a non-live host.  Previously a warning was only given if `--verbose` was specified.
This should never happen since the changes detailed in github issue #67, and if it does happen the user should know about it.
=> Always warn if remove_host() is called on a non-live host

ChangeLog, NEWS.md, arp-scan.c
Change the informational message about the interface network and netmask used to generate the target list when --localnet is used, and always display this message (previously it was only displayed if --verbose was given).
Old message was: `Using 10.0.0.0:255.255.255.0 for localnet`.
New message is: `Target list from interface network 10.0.0.0 netmask 255.255.255.0`
=> Change --localnet info message and always display it

ChangeLog, NEWS.md, arp-scan.1.dist, arp-scan.c, arp-scan.h
Add `${IPnum}` output field to display the host IPv4 address as a 32-bit integer.
Issue ref: #156
=> Add ${IPnum} output field

ChangeLog, arp-scan.c
Flush the stdout buffer after displaying each responding hosts. This ensures that responding hosts are available immediately when reading `arp-scan` output from a pipeline.
=> Flush stdout buffer after displaying each responding host
